import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ContextProvider } from "./shared/providers/theme-provider";
import ThemeLayout from "@/components/theme-layout";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ContextProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={`dark:bg-gray-900 p-5 ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <script
            dangerouslySetInnerHTML={{
              __html: `
                (function() {
                  try {
                    var theme = localStorage.getItem('theme');
                    console.log(theme)
                    if (theme === 'dark') {
                      document.documentElement.classList.add('dark');
                    } else {
                      document.documentElement.classList.remove('dark');
                    }
                  } catch (e) {}
                })();
              `,
            }}
          />
          <ThemeLayout>{children}</ThemeLayout>
        </body>
      </html>
    </ContextProvider>
  );
}
