import { ErrorTooltip } from '@/_shared/components/ErrorTooltip';
import { Header } from '@/_shared/components/Header';
import type { Metadata } from 'next';

import { geistMono, geistSans } from '@/_shared/fonts/fonts';
import { getSession } from '@/_shared/lib/auth';
import '@/globals.css';
import { APIError } from 'better-auth';
import { cookies, headers } from 'next/headers';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const SESSION_TOKEN_NAME = 'better-auth.session_token' as const;

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let session = null;
  let e: any;
  const cookieStore = (await cookies()).has(SESSION_TOKEN_NAME);

  try {
    if (cookieStore) return;
    const { data, error } = await getSession({
      fetchOptions: {
        headers: await headers(),
        credentials: 'include',
      },
    });
    e = error;
    session = data;
  } catch (err: any) {
    e = new APIError().status;
  }

  if (!session) {
    redirect('/login');
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark:bg-gray-900 ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header user={session?.user ?? null} />
        {e && <ErrorTooltip error={e} />}
        {children}
      </body>
    </html>
  );
}
